### ISSUE TITLE
Load Content method

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/akumina-mynci#12]
## Summary

Create a `loadContent` method on the `DrupalContent` class that will load the content from the specified XML files and update the `DrupalContent` object (which already has properties for the different content types) with the parsed data from the XML files.

## Inputs

- Object with file paths for each content type:

```
{ blogs = "../path/to/file.xml", events = "../path/to/file.xml" }
```

## Outputs

None. The result should be that the instantiated `DrupalContent` object has the specified content loaded to it.

## Tasks

- [ ] Create a `migration/content` directory and add it to the `.gitignore` so we're not checking it in (you'll want to put a `README.txt` and allow that in `.gitignore` so the directory checks in to git)
- [ ] Update the stubbed out code (linked below) to load each of the content files into the appropriate array on the DrupalContent object
- [ ] To do so, create a new `loadFile` method that does the actual parsing, given a file path. That way the `loadContent` method can just call `loadFile()` for each of the different files and place the results back into the correct object. This code would be moved into that method:

```node
      const filePath = './__mocks/export_content.xml';
      const xmlData = await fsPromises.readFile(filePath);

      const parser = new xml2js.Parser();
      const results = await parser.parseStringPromise(xmlData);
```

Here is the stubbed out code. (Note, I don't think the JSdoc  `@param`s on there are completely correct.)

https://github.com/NCIOCPL/akumina-mynci/blob/5cd21e8d6eec5370ce899f4f71b63edaa76d7ee5/migration/src/lib/drupal-content.js#L21-L44
